// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCbLCfsr-xgkBa8umw4NXJN1-jvi9F2f4',
    appId: '1:160547826214:web:186b77e0151b46013c54e7',
    messagingSenderId: '160547826214',
    projectId: 'mynotes-d9fe8',
    authDomain: 'mynotes-d9fe8.firebaseapp.com',
    storageBucket: 'mynotes-d9fe8.appspot.com',
    measurementId: 'G-6PS26GB4RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_u66fVC_bSq_ddHDTQX4pIhFJKtHLG2M',
    appId: '1:160547826214:android:e124f0583e9438cd3c54e7',
    messagingSenderId: '160547826214',
    projectId: 'mynotes-d9fe8',
    storageBucket: 'mynotes-d9fe8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6jjXvR7WCe_9eZ4CyxOX0f8LHu8UJ0W8',
    appId: '1:160547826214:ios:8a220e3acfe447783c54e7',
    messagingSenderId: '160547826214',
    projectId: 'mynotes-d9fe8',
    storageBucket: 'mynotes-d9fe8.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6jjXvR7WCe_9eZ4CyxOX0f8LHu8UJ0W8',
    appId: '1:160547826214:ios:c7bdac9575768ad33c54e7',
    messagingSenderId: '160547826214',
    projectId: 'mynotes-d9fe8',
    storageBucket: 'mynotes-d9fe8.appspot.com',
    iosBundleId: 'com.example.mynotes.RunnerTests',
  );
}
